### ISSUE TITLE
Insufficient permissions on Cronjobs results in Database failing to turn healthy

### ISSUE THREAD

**Issue by Eliaxie** [db-operator/charts#73]
Hello,
We noticed in one of our Databases that the operator was struggling to set the status.status field to true.
This is our Database:
```
apiVersion: kinda.rocks/v1beta1
kind: Database
metadata:
  name: db
spec:
  secretName: db-creds
  instance: db-instance
  deletionProtected: true
  postgres:
    extensions:
      - pgaudit
  backup:
    enable: true
    cron: "0 0 * * *"
  cleanup: true
```
The only log present in the operator was
```
Failed to watch \*v1.CronJob: failed to list \*v1.CronJob: cronjobs.batch is forbidden: User "system:serviceaccount:db-operator:db-operator" cannot list resource "cronjobs" in API group "batch" at the cluster scope
```
And indeed adding the list permission on cronjobs fixed our issue:
```
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - update
  - list # This is missing in the helm chart and results in errors in the operator.
```
Unfortunately the codepath inside the operator was not logged but my guess is that the backup cronjob had something to do with it.
Let me know if you find the cause of this and/or if you want me to create a PR with the changes.
Thanks!
